---
minimum_pre_commit_version: "1.15"
default_stages: [commit]

repos:
#: -------------------------------------------------------------------------------------
#: General hooks
#: -------------------------------------------------------------------------------------
  #: Find TODO:|FIXME:|BUG: comments in all files
  #: Inline skip: `#i#` directly after the colon after the tag-word
  - repo: local
    hooks:
      - id: find-todos
        name: 'Find TODO:|FIXME:|BUG: comments'
        description: 'Check for TODO:|FIXME:|BUG: comments in all files'
        language: pygrep
        entry: '(^|//|#|<!--|;|/\*|\.\.)\s*(TODO:|FIXME:|BUG:)(?!#i#)'
        exclude: 'TODO'

  #: code unspecific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
        args: ["--indent=4", "--autofix"]
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]


#: -------------------------------------------------------------------------------------
#: Python hooks
#: -------------------------------------------------------------------------------------
      - id: name-tests-test
        args: ["--django"]

  #: several python code regex hooks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce  # frozen: v1.9.0
    hooks:
      - id: python-no-log-warn
      - id: python-no-eval

  #: pyupgrade - upgrade old python syntax to new
  - repo: https://github.com/asottile/pyupgrade
    rev: c1b1c5380dbb12b30ec0d0652df204d21ae003b8  # frozen: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  #: isort - sort imports
  #: Inline skip: `# isort: skip`
  - repo: https://github.com/PyCQA/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
    hooks:
      - id: isort

  #: black - python formatter
  #: Inline skip: mark block with `# fmt: off` and `# fmt: on` (same indent)
  - repo: https://github.com/psf/black
    rev: 27d20144a7517594e24a1649451177b2a11284be  # frozen: 22.10.0
    hooks:
      - id: black
        args: [--safe]

  #: Lint hooks managed via tox `pre-commit` env b/c they need the pkg installed
  - repo: local
    hooks:
      #: mypy - python type checker
      #: Skip file: `# type: ignore` at top
      #: Inline skip: `# type: ignore` or `# type: ignore[CODE, ...]`
      - id: mypy
        name: mypy
        description: run mypy over the installed version if available
        entry: env_exe_runner tox,.venv pre_commit mypy
        args: ["--config-file=tox.ini"]
        language: system
        types: [python]
        require_serial: true
      #: flake8 - python linter
      #: File skip: `# flake8: noqa`
      #: Inline skip: `# noqa` or `# noqa: CODE,...`
      - id: flakehell
        name: flakehell
        description: run flakehell over the installed version if available
        entry: env_exe_runner tox,.venv pre_commit flakehell
        args: [lint, "--safe"]
        language: system
        types: [python]
        require_serial: true

  #: pylint - python linter
  #: File skip: `# pylint: skip-file`
  #: Inline change: `# pylint: disable|enable=CODE|NAME`
  - repo: https://github.com/PyCQA/pylint/
    rev: b2af2b299c1206e035f44db90b1569b3e3b13511  # frozen: v2.15.6
    hooks:
      - id: pylint
        name: spell-check (pylint+pyenchant)
        description: >
          spell-check in docstrings/comments in py-source via pyenchant and pylint
        args: ["--disable=all", "--enable=spelling"]
        additional_dependencies: [pyenchant]
        exclude: '^(?!src).*'


#: -------------------------------------------------------------------------------------
#: Docu hooks
#: -------------------------------------------------------------------------------------
  #: blacken-docs - black for python code in docs
  - repo: https://github.com/asottile/blacken-docs
    rev: 7ae9389351f4090e3993de28015a05a18ca6b8a7  # frozen: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]

  #: rstcheck - rst file checker
  - repo: https://github.com/rstcheck/rstcheck
    rev: 77751d7a7d81a5d47aa344d802f41809c4d063c0  # frozen: v6.1.1
    hooks:
      - id: rstcheck
        additional_dependencies: ["sphinx"]
        args: ["--config=tox.ini"]


#: -------------------------------------------------------------------------------------
#: Poetry hooks
#: -------------------------------------------------------------------------------------
  # poetry - python dependency management
  - repo: https://github.com/Cielquan/mirrors-poetry
    rev: 7e519d0e66da9e078ffd2a06eacac5d88d31ac63  # frozen: 1.2.2
    hooks:
      - id: poetry-check


#: -------------------------------------------------------------------------------------
#: YAML hooks
#: -------------------------------------------------------------------------------------
  #: yamllint - yaml linter
  #: Inline skip: `# yamllint disable-line[ rule:<RULE>]`
  #: Block skip: `# yamllint disable[ rule:<RULE>]`
  #: Block skip end: `# yamllint enable`
  - repo: https://github.com/adrienverge/yamllint
    rev: 9cce2940414e9560ae4c8518ddaee2ac1863a4d2  # frozen: v1.28.0
    hooks:
      - id: yamllint


#: -------------------------------------------------------------------------------------
#: Meta hooks
#: -------------------------------------------------------------------------------------
  #: Meta hooks provided by pre-commit
  - repo: meta
    hooks:
      - id: identity
        stages: [commit, manual]
      - id: check-hooks-apply
        stages: [manual]
      - id: check-useless-excludes
        stages: [manual]
