---
name: Update AUTHORS.rst

# What this workflow does:
# 1. Update the AUTHORS.rst file
# 2. Git commit and push the file if there are changes.

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

  push:
    tags:
      - "!*"
    branches:
      - main
      - "test-me-*"

jobs:
  update-authors:
    name: Update AUTHORS file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Set git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: Update AUTHORS file
        shell: python
        run: |
          import subprocess

          git_authors = subprocess.run(
              ["git", "log", "--format=%aN <%aE>"], capture_output=True, check=True
          ).stdout.decode()

          authors = [
              author
              for author in set(git_authors.strip().split("\n"))
              if not author.startswith(("dependabot", "pre-commit-ci", "github-action"))
          ]
          authors.sort()

          file_head = (
              "# This file contains all the individuals who contributed to this "
              "repository.\n"
              "# This file is automatically generated/updated by a github actions "
              "workflow.\n"
              "# Every manual change will be overwritten on push to main.\n"
              "# You can find it here: `.github/workflows/update-authors.yml`\n\n"
          )

          with open("AUTHORS", "w") as authors_file:
              authors_file.write(file_head)
              authors_file.write("\n".join(authors))
              authors_file.write("\n")

      - name: Commit and push if diff
        # yamllint disable rule:line-length
        run: >
          git diff --exit-code AUTHORS &&
          (echo "### No update" && exit 0) || (echo "### Commit update" &&
          git reset HEAD -- . &&
          git add AUTHORS &&
          git commit -m 'Update AUTHORS file with new author(s) [skip ci]' &&
          git push "https://${{ github.repository_owner }}:$GITHUB_TOKEN@github.com/${{ github.repository }}.git")
        # yamllint enable
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
